#!/usr/bin/env bun
/**
 * Generate build-info.generated.ts with git hash, dirty state, and build timestamp.
 * The timestamp is refreshed on every explicit generation so compiled binaries report the actual build time.
 */

const outputPath = new URL("../src/build-info.generated.ts", import.meta.url).pathname;

async function gitCommand(args: string[]): Promise<string | null> {
	try {
		const proc = Bun.spawn(["git", ...args], {
			stdout: "pipe",
			stderr: "pipe",
		});
		const exitCode = await proc.exited;
		if (exitCode !== 0) return null;
		return (await new Response(proc.stdout).text()).trim();
	} catch {
		return null;
	}
}

const [hashResult, statusResult] = await Promise.all([
	gitCommand(["rev-parse", "--short", "HEAD"]),
	gitCommand([
		"status",
		"--porcelain",
		"--untracked-files=no",
		"--",
		":!packages/coding-agent/scripts/generate-build-info.ts",
	]),
]);

const gitHash = hashResult ?? "unknown";
const dirty = hashResult !== null && statusResult !== null && statusResult.length > 0;

const buildTimestamp = new Date().toISOString();

const output = `// Auto-generated by scripts/generate-build-info.ts - DO NOT EDIT
export const BUILD_INFO = {
	projectName: "ohp",
	gitHash: "${gitHash}",
	dirty: ${dirty},
	buildTimestamp: "${buildTimestamp}",
} as const;
`;

await Bun.write(outputPath, output);
console.log(`Generated build-info.generated.ts (${gitHash}${dirty ? " dirty" : ""})`);
