#!/usr/bin/env bun
/**
 * Generate build-info.generated.ts with git hash, dirty state, and build timestamp.
 * Preserves existing timestamp if hash and dirty state haven't changed.
 */

const outputPath = new URL("../src/build-info.generated.ts", import.meta.url).pathname;

async function gitCommand(args: string[]): Promise<string | null> {
	try {
		const proc = Bun.spawn(["git", ...args], {
			stdout: "pipe",
			stderr: "pipe",
		});
		const exitCode = await proc.exited;
		if (exitCode !== 0) return null;
		return (await new Response(proc.stdout).text()).trim();
	} catch {
		return null;
	}
}

const [hashResult, statusResult] = await Promise.all([
	gitCommand(["rev-parse", "--short", "HEAD"]),
	gitCommand(["status", "--porcelain"]),
]);

const gitHash = hashResult ?? "unknown";
const dirty = hashResult !== null && statusResult !== null && statusResult.length > 0;

// Check existing file for matching hash+dirty to preserve timestamp
let existingHash: string | null = null;
let existingDirty: boolean | null = null;

const file = Bun.file(outputPath);
if (await file.exists()) {
	try {
		const content = await file.text();
		const hashMatch = content.match(/gitHash:\s*"([^"]+)"/);
		const dirtyMatch = content.match(/dirty:\s*(true|false)/);
		if (hashMatch) existingHash = hashMatch[1];
		if (dirtyMatch) existingDirty = dirtyMatch[1] === "true";
	} catch {
		// Malformed file — will rewrite
	}
}

if (existingHash === gitHash && existingDirty === dirty) {
	console.log("build-info.generated.ts unchanged (hash and dirty state match)");
	process.exit(0);
}

const buildTimestamp = new Date().toISOString();

const output = `// Auto-generated by scripts/generate-build-info.ts - DO NOT EDIT
export const BUILD_INFO = {
	projectName: "ohp",
	gitHash: "${gitHash}",
	dirty: ${dirty},
	buildTimestamp: "${buildTimestamp}",
} as const;
`;

await Bun.write(outputPath, output);
console.log(`Generated build-info.generated.ts (${gitHash}${dirty ? " dirty" : ""})`);
